version: "3"

services:
  fullstack:
    image: "public.ecr.aws/j2m0y8o3/dashboard:latest"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    entrypoint: ["npm", "run", "dev"]

  test:
    image: "public.ecr.aws/j2m0y8o3/dashboard:latest"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    entrypoint: ["npm", "test"]