version: "3"

services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: "dashboard:latest"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    entrypoint: ["npm", "run", "dev"]

  test:
    image: "dashboard:latest"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    depends_on: 
      - fullstack
    entrypoint: ["npm", "test"]