export class DataPoint {
  name: string;
  value: string;
  description?: string;
}

export const imageDirectory = {
  "House Need": "public/images/axis-icons/sdg-11.1.1.png",
  Transit: "public/images/axis-icons/sdg-11.2.1.png",
  Consumption: "public/images/axis-icons/sdg-11.3.1.png",
  Civility: "public/images/axis-icons/sdg-11.3.2.png",
  Affected: "public/images/axis-icons/sdg-11.5.1.1.png",
  Disaster: "public/images/axis-icons/sdg-11.5.1.2.png",
  "Econ Loss1": "public/images/axis-icons/sdg-11.5.2.png",
  "Econ Loss2": "public/images/axis-icons/sdg-11.5.2.png",
  Waste: "public/images/axis-icons/sdg-11.6.1.png",
  PM: "public/images/axis-icons/sdg-11.6.2.png",
  // TODO: Add 11.7.1
  Assult: "public/images/axis-icons/sdg-11.7.2.png",
};

export class DataModel {
  name: string;
  data: DataPoint[];
}

export class Data {
  /** Return the max value of all DataModel.DataPoint.values */
  static getAbsoluteMax(data: DataModel[]): number {
    const nonFlatArrOfNumbers = data.map((d) =>
      d.data.map((x) => Number(x.value))
    );
    return Math.max(...this.flat(nonFlatArrOfNumbers));
  }

  private static flat(nestedArray: number[][]): number[] {
    return [].concat.apply([], nestedArray);
  }

  /** Given a DataModel[], get the max value of every common data.name variable */
  static getMaxPerVariable(data: DataModel[]): number[] {
    return this.runOperationOnGroupOfVariables(data, Math.max);
  }

  /** Given a DataModel[], get the min value of every common data.name variable */
  static getMinPerVariable(data: DataModel[]): number[] {
    return this.runOperationOnGroupOfVariables(data, Math.min);
  }

  private static runOperationOnGroupOfVariables(data: DataModel[], operation) {
    const numberMatrix = data.map((d) => d.data.map((x) => Number(x.value)));
    let maxOfVariable: number[] = [];
    for (let i in numberMatrix[0]) {
      let groupValuesByVariable = numberMatrix.map((d) => d[i]);
      maxOfVariable.push(operation(...groupValuesByVariable));
    }
    return maxOfVariable;
  }

  /**
   * @returns   Returns all geographic data as an array of Data Model.
   * \details   Each DataModel element pertains to one city, and has a name and data property.
   *              - The data property is an array of DataPoint
   *              - Each DataPoint has three strings (name, desc, value) for the bar plot.
   */
  static getSyncData(): DataModel[] {
    return [
      {
        name: "St. John's",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.196",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.41912307",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.3375",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.397905759",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.967883133",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.735469986",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.980259785",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.978409898",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.583333333",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Halifax",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.2",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.401851333",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.282722513",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.758780432",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.991863667",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.991563022",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.274314214",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.583333333",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Quebec City",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.072",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.555142299",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.4288",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.623036649",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.849684887",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.678591369",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.992612202",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.992181355",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.578553616",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.416666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Sherbrooke",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.2",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.20953882",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.2546",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.623036649",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.946702839",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.567493002",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.998054561",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.997941172",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.411471322",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Montreal",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.116",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.542826593",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.3645",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.429319372",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.199575696",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.667494914",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.962036346",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.959823367",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.790523691",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.416666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Toronto",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.12",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.973481553",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.4039",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.035948184",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.724149925",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.472314916",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.447432205",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.825436409",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.75",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Hamilton",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.088",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.597523622",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.153",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.319371728",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.914932794",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.809926691",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.992682509",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.992337456",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.528678304",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.916666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "St. Catharines, Niagara",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.124",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.003333298",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.2423",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.272251309",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.954073194",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.811198662",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.99605296",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.995866839",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.523690773",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.5",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Kitchener, Cambridge, Waterloo",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.108",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.920192018",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.1522",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.403141361",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.940800328",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.808982728",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.99492853",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.994689387",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.655860349",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "London",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.128",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.647486682",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.1831",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.272251309",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.944031391",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.810418937",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.995194437",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.994967834",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.443890274",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Windsor",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.068",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.041724498",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.3367",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.387434555",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.952197311",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.760131164",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.996747006",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.996593613",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.179551122",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.416666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Winnipeg",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.168",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.653474212",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.0082",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.366492147",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.98678976",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.97091365",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.617834473",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.605963669",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.705735661",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Regina",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.076",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.600212968",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.1563",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.303664921",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.993824603",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.954228525",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.975137073",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.972506065",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.760598504",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.083333333",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Saskatoon",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.128",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.728664635",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.382198953",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.999728535",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.998379091",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.966749603",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.963441872",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.566084788",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.583333333",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Calgary",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.192",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "1.037835577",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.2922",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.408376963",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.969706496",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.961429024",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.204076288",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.146420409",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.72319202",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Edmonton",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.144",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.842841747",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.1443",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.356020942",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.999265422",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.999015336",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.995613356",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.80",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.568578554",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.416666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "0.80",
          },
        ],
      },
      {
        name: "Vancouver",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.22",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "1.023418723",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.4772",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.078534031",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.464536408",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.630853372",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.839610176",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.829440932",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.817955112",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
      {
        name: "Victoria",
        data: [
          {
            name: "PM",
            description:
              "Average fine particule matter concentrations (PM 2.5)",
            value: "1.228",
          },
          {
            name: "Consumption",
            description:
              "Ratio of land consumption rate to population growth rate (1971 to 2011)",
            value: "0.929264945",
          },
          {
            name: "Assult",
            description: "Sexual assault (rate per 100,000 population)",
            value: "0.2873",
          },
          {
            name: "House Need",
            description: "Proportion of households in core housing need",
            value: "0.256544503",
          },
          {
            name: "Affected",
            description: "Total Affected",
            value: "0.967908252",
          },
          {
            name: "Disaster",
            description:
              "Number of people who died, went missing or were directly affected by disasters per 100,000 population.",
            value: "0.851679244",
          },
          {
            name: "Econ Loss1",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Canadian Disaster Database)",
            value: "0.987398785",
          },
          {
            name: "Econ Loss2",
            description:
              "Direct economic loss: the monetary value of total or partial destruction of physical assets existing in the affected area. Direct economic loss is nearly equivalent to physical damage (based on the Inflation Calculator)",
            value: "0.987105407",
          },
          {
            name: "Transit",
            description:
              "Percentage of population less than 500 metres from public transit access point. ",
            value: "0.760598504",
          },
          {
            name: "Civility",
            description:
              "Proportion of cities with a direct participation structure of civil society in urban planning and management that operate regularly and democratically ",
            value: "0.666666667",
          },
          {
            name: "Waste",
            description:
              "Proportion of urban solid waste regularly collected and with adequate final discharge out of total urban solid waste generated by cities ",
            value: "1.0",
          },
        ],
      },
    ];
  }
}
