# This is a basic workflow to help you get started with Actions

name: Remote SSH Command

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: server
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: whoami

      # - uses: actions/checkout@v2
      # # Runs a single command using the runners shell
      # - name: SSH into server
      #   with:
      #     command: |
      #       cd Documents
      #       ls -a
      #     host: ${{ secrets.IP }}
      #     user: server
      #     key: ${{ secrets.SSH_KEY}}

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
